services:
  payment-provider-gln:
    image: payment-provider-gln:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"